kind: pipeline
type: docker
name: dev

steps:
  - name: build
    image: 192.168.0.212:5000/plugins/docker:21
    settings:
      tags: ${DRONE_TAG}
      dockerfile: Dockerfile
      registry: 192.168.0.212:5000
      repo: 192.168.0.212:5000/gov-id-tracker-web
      insecure: true
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

trigger:
  branch:
    - master

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
