import "@mantine/core/styles.css";
import "@mantine/dropzone/styles.css";
import "@mantine/carousel/styles.css";

import { ModalsProvider } from "@mantine/modals";
import type { Metadata } from "next";
import LoadingLayout from "@/layout/loading";
import QueryClientProvider from "@/provider/QueryClientProvider";
import {
  ColorSchemeScript,
  Flex,
  MantineProvider,
  createTheme,
  mantineHtmlProps,
} from "@mantine/core";
import { SessionProvider, useSession } from "next-auth/react";
import { PropsWithChildren } from "react";
import { theme } from "@/layout/theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps extends PropsWithChildren {}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <SessionProvider>
          <QueryClientProvider>
            <MantineProvider theme={theme}>
              <ModalsProvider>
                <LoadingLayout>
                  <Flex h={"100vh"} w={"100%"}>
                    {" "}
                    {children}
                  </Flex>
                </LoadingLayout>
              </ModalsProvider>
            </MantineProvider>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
