import "@mantine/core/styles.css";
import { ModalsProvider } from '@mantine/modals';
import type { Metadata } from "next";

import QueryClientProvider from "@/provider/QueryClientProvider";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { SessionProvider } from "next-auth/react";
import { PropsWithChildren } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayoutProps extends PropsWithChildren {

}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <SessionProvider>
          <QueryClientProvider>
            <MantineProvider>
              <ModalsProvider> {children}</ModalsProvider>
            </MantineProvider>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
